"use client";

import { useEffect, useState } from "react";
import { BellRing, Check, Clipboard, ExternalLink, Radio, ShieldCheck, Zap } from "lucide-react";

type EventData = { taskName: string; taskId: string; previousStatus: string; currentStatus: string; receivedAt: string };
type WatchStatus = { configured: boolean; webhookReady: boolean; latestEvent: EventData | null };
const listId = "901816752697";
const validateStatusId = "sc901816752697_xMTGXVI";

export default function Home() {
  const [status, setStatus] = useState<WatchStatus>({ configured: false, webhookReady: false, latestEvent: null });
  const [copied, setCopied] = useState(false);
  useEffect(() => { const loadStatus = () => fetch("/api/clickup/status").then((response) => response.json()).then(setStatus).catch(() => undefined); loadStatus(); const interval = window.setInterval(loadStatus, 10000); return () => window.clearInterval(interval); }, []);
  const copyStatusId = async () => { await navigator.clipboard.writeText(validateStatusId); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };

  return <main className="mx-auto flex min-h-screen w-full max-w-[1440px] flex-col px-5 py-6 sm:px-8 lg:px-12 lg:py-10">
    <header className="flex items-center justify-between border-b border-[var(--line)] pb-6"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-[var(--mint)] text-[#07141b]"><BellRing size={20} strokeWidth={2.5} /></div><div><p className="text-sm font-semibold tracking-[0.16em] text-[var(--mint)] uppercase">Validate Watch</p><p className="mt-0.5 text-xs text-[var(--muted)]">ClickUp task signals</p></div></div><div className="flex items-center gap-2 text-xs text-[var(--muted)]"><span className={`size-2 rounded-full ${status.webhookReady ? "bg-[var(--mint)] shadow-[0_0_14px_var(--mint)]" : "bg-[var(--coral)]"}`} />{status.webhookReady ? "Listening" : "Awaiting webhook"}</div></header>
    <section className="grid flex-1 gap-14 py-14 lg:grid-cols-[minmax(0,1.1fr)_minmax(380px,0.9fr)] lg:items-center lg:gap-20 lg:py-20"><div className="animate-[rise_700ms_ease-out_both]"><p className="mb-6 flex items-center gap-2 text-xs font-bold tracking-[0.22em] text-[var(--coral)] uppercase"><span className="h-px w-8 bg-[var(--coral)]" /> Status automation / 01</p><h1 className="max-w-3xl text-5xl font-semibold leading-[0.98] tracking-[-0.05em] text-[#eff7f0] sm:text-7xl">A quiet ping when work reaches <span className="text-[var(--mint)]">validate.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-[var(--muted)] sm:text-lg">This watch listens to one ClickUp list and surfaces the instant a task enters validation, so the next person can move without checking another tab.</p><div className="mt-10 flex flex-wrap gap-3"><a href={`https://app.clickup.com/90181299888/v/l/6-${listId}-1`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[var(--mint)] px-5 py-3 text-sm font-bold text-[#07141b] transition-transform hover:-translate-y-0.5">Open ClickUp list <ExternalLink size={16} /></a><button onClick={copyStatusId} className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] px-5 py-3 text-sm font-semibold text-[#d8e8df] transition-colors hover:border-[var(--mint)]">{copied ? <Check size={16} /> : <Clipboard size={16} />} {copied ? "Copied" : "Copy status ID"}</button></div></div>
    <div className="animate-[rise_700ms_180ms_ease-out_both] rounded-2xl border border-[var(--line)] bg-[#0b2027]/85 p-6 shadow-2xl shadow-black/20 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-[0.18em] text-[var(--muted)] uppercase">Signal monitor</p><p className="mt-2 text-2xl font-semibold tracking-[-0.03em]">Validation gateway</p></div><Radio className="text-[var(--mint)]" size={24} /></div><div className="mt-8 border-y border-[var(--line)] py-5"><div className="flex items-center justify-between text-xs text-[var(--muted)]"><span>Current watch</span><span className="font-mono text-[var(--mint)]">LIVE</span></div><div className="mt-4 flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-[#173943] text-[var(--mint)]"><Zap size={17} /></span><div><p className="text-sm font-semibold">Task status changes</p><p className="mt-1 text-xs text-[var(--muted)]">→ Validate</p></div></div></div><div className="grid grid-cols-2 gap-3 py-5"><Metric label="List" value={listId} /><Metric label="Status ID" value={validateStatusId.slice(-8)} mono /></div><div className="rounded-xl bg-[#07171e] p-4"><div className="flex items-center gap-2 text-xs font-semibold text-[var(--muted)]"><ShieldCheck size={15} className="text-[var(--mint)]" /> Latest matching event</div>{status.latestEvent ? <div className="mt-4"><p className="text-sm font-semibold">{status.latestEvent.taskName}</p><p className="mt-1 text-xs text-[var(--muted)]">{status.latestEvent.previousStatus} <span className="px-1 text-[var(--coral)]">→</span> {status.latestEvent.currentStatus}</p><p className="mt-3 text-[11px] text-[var(--muted)]">{new Date(status.latestEvent.receivedAt).toLocaleString()}</p></div> : <p className="mt-4 text-sm text-[var(--muted)]">No validation events received yet.</p>}</div></div></section>
    <footer className="grid gap-4 border-t border-[var(--line)] pt-6 text-xs text-[var(--muted)] sm:grid-cols-3"><p>01 / listening for a precise transition</p><p className="sm:text-center">last checked just now</p><p className="sm:text-right">built for your ClickUp list</p></footer>
  </main>;
}

function Metric({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="rounded-lg border border-[var(--line)] p-3"><p className="text-[10px] font-bold tracking-[0.16em] text-[var(--muted)] uppercase">{label}</p><p className={`mt-2 truncate text-xs text-[#d8e8df] ${mono ? "font-mono" : ""}`}>{value}</p></div>; }
